steps:
  - label: ":python: Validate Streamlit Code"
    command: 
      - "pip install -r streamlit_app/app_final/requirements.txt"
      - "python -m py_compile streamlit_app/app_final/app.py"
    agents:
      queue: "windows-runner"

  - wait: ~

  - block: ":rocket: Approve Deployment"
    prompt: "Does the dashboard look good to merge?"

  - label: ":streamlit: Deploy"
    command: "echo 'Deployment step executed!'"
    agents:
      queue: "windows-runner"
